import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Nav from "~/Components/Nav/nav";
import raleway from "~/utils/fonts";

import { api } from "~/utils/api";


const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
        <Head>
            <title>Create T3 App</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col bg-white">
            <Nav/>
        </main>
    </>
  );
};

export default Home;
